### ISSUE TITLE
missing required value config->user->projects_dir

### ISSUE THREAD

**Issue by raamdev** [websharks/cli-tools#2]
I got the following error when running `ws` (no arguments):

```
/Users/raam/.websharks.json is missing required value config->user->projects_dir. See: <http://bit.ly/1zt2n32>
```

My `~/.websharks.json` contained the "required missing value":

```
{
    "config": {
        "user": {
            "name": "raamdev",
            "projectsDir": "~/Projects"
        },
.....
```

You'll notice the key name is `projectsDir` in my config file but the cli tools are looking for `projects_dir`. 

No big deal; I just updated my config file to use `projects_dir` and the cli tools work now, however I wanted to point out that the link referenced in that error message points to an example that uses `projectsDir` (which is what I had and which was not working): https://github.com/websharks/dotfiles/blob/000000-dev/.websharks.json

**Comment by jaswrks** [comment]
Thanks for the heads up. I updated this example, because I changed from camelCase to underscores in this file a while back, but I forgot to update the example. Sorry! https://github.com/websharks/dotfiles/blob/000000-dev/.websharks.json
