### ISSUE TITLE
Shorten should only output shortened link

### ISSUE THREAD

**Issue by raamdev** [websharks/cli-tools#4]
```
$ ws shorten http://www.websharks-inc.com/
<http://wsharks.com/1dXgBaW>
$ ws shorten http://www.websharks-inc.com/ | pbcopy
# Contents of clipboard: [0;39m[49m<[4;34mhttp://wsharks.com/1dXgBaW[0m[0;39m>[0m
```

Because the `ws shorten` command outputs the URL with `<` and `>`, you cannot pipe the command into a tool like `pbcopy` to easily copy the shortened URL to your clipboard on a Mac. (In fact, it would be awesome if `ws shorten` copied the shortened URL to your clipboard automatically... edit: see #5)

**Comment by jaswrks** [comment]
Added in the release of v160110.
https://github.com/websharks/cli-tools/releases/tag/160110
