### ISSUE TITLE
Feature Request: pbcopy and pbpaste integration for Shorten

### ISSUE THREAD

**Issue by raamdev** [websharks/cli-tools#5]
As mentioned in #4, it would be awesome if `ws shorten` copied the shortened URL to your clipboard automatically after running the shorten command. On a Mac, this can be done by piping the URL into the `pbcopy` command.

Along these same lines, it would be awesome if `ws shorten` also checked my clipboard to see if what's on the clipboard is a URL (on a Mac that could be done with the `pbpaste` command) and if it's a URL and I haven't passed any URL argument to the `ws shorten` command, the URL on my clipboard would be shortened.

This would greatly improve the workflow of shortening a URL using the command line. Right now the workflow looks like this:
1. Copy URL to shorten
2. Type `ws shorten` on the command line
3. Paste in the URL
4. Press return
5. Select and copy the shortened URL (because of #4). 

By fixing #4 and adding the enhancements described here, we could shorten these steps to:
1. Copy URL to shorten
2. Type `ws shorten` on the command line
3. Press return

**Comment by jaswrks** [comment]
:+1:

**Comment by jaswrks** [comment]
Added in the release of v160110.
https://github.com/websharks/cli-tools/releases/tag/160110
